// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuSeRipZfUDQpl1snpuP-O3uy0qPrwiQM',
    appId: '1:305238383244:web:80d332d6f44dbd70a779a9',
    messagingSenderId: '305238383244',
    projectId: 'healthsdfsdfsdfsdf',
    authDomain: 'healthsdfsdfsdfsdf.firebaseapp.com',
    storageBucket: 'healthsdfsdfsdfsdf.firebasestorage.app',
    measurementId: 'G-1JVDKJX075',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGorF2uhtT8dD2wuBhFP1zghMjqHqujg0',
    appId: '1:305238383244:android:c3422a66d043b356a779a9',
    messagingSenderId: '305238383244',
    projectId: 'healthsdfsdfsdfsdf',
    storageBucket: 'healthsdfsdfsdfsdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClmdRi0oZuE9M3zBtO2_91QMCDGaOya08',
    appId: '1:305238383244:ios:f043978d9bbb0805a779a9',
    messagingSenderId: '305238383244',
    projectId: 'healthsdfsdfsdfsdf',
    storageBucket: 'healthsdfsdfsdfsdf.firebasestorage.app',
    iosClientId: '305238383244-eqdb86hn0o718l751pndio3unanodjtl.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
